name: Build

on:
  push:
    paths:
      - ".github/workflows/build.yml"
      - "key/**"
      - "main/**"
      - "power-reset/**"
  pull_request:
    paths:
      - ".github/workflows/build.yml"
      - "key/**"
      - "main/**"
      - "power-reset/**"

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: docker.io/setsoft/kicad_auto:dev_k6
    strategy:
      fail-fast: false
      matrix:
        pcb: [main, key, power-reset]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build
        run: cd ${{ matrix.pcb }} && kibot -v
      - name: Archive Gerbers
        uses: actions/upload-artifact@v3
        with:
          name: asetniopy-${{ matrix.pcb }}-gerbers
          path: |
            ${{ matrix.pcb }}/JLCPCB/*
            !${{ matrix.pcb }}/JLCPCB/*.zip
      - name: Archive Assembly Files
        uses: actions/upload-artifact@v3
        with:
          name: asetniopy-${{ matrix.pcb }}-assembly
          path: |
            ${{ matrix.pcb }}/*.csv
      - name: Archive Renders
        uses: actions/upload-artifact@v3
        with:
          name: asetniopy-${{ matrix.pcb }}-renders
          path: |
            ${{ matrix.pcb }}/*.png
            ${{ matrix.pcb }}/*.svg
            ${{ matrix.pcb }}/*.step
