name: Build

on:
  push:
    paths:
      - ".github/workflows/build.yml"
      - "key/**"
      - "main/**"
      - "power-reset/**"
  pull_request:
    paths:
      - ".github/workflows/build.yml"
      - "key/**"
      - "main/**"
      - "power-reset/**"

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: docker.io/setsoft/kicad_auto:dev_k6
    strategy:
      fail-fast: false
      matrix:
        pcb: [main, key, power-reset]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: cd ${{ matrix.pcb }} && kibot -vv
      - name: Archive
        uses: actions/upload-artifact@v2
        with:
          name: asetniopy-${{ matrix.pcb }}
          path: |
            ${{ matrix.pcb }}/JLCPCB/*
            !${{ matrix.pcb }}/JLCPCB/*.zip
